mpi-1.0: exit early when passed a removed variant
This change checks to see if a variant was passed that was explicitly banned,
e.g.

mpi.setup -openmpi

and then if a user runs 'port install gnudatalanguage +openmpi' they will now
be informed:

Error: gnudatalanguage has disallowed +openmpi! Please choose another mpi variant
Error: Unable to open port: gnudatalanguage +openmpi not allowed

This is done early so that dependencies aren't compiled with an undesired mpi.


git-svn-id: https://svn.macports.org/repository/macports/trunk@121954 d073be05-634f-4543-b044-5fe20cf6d1d6