netpbm: update to 10.64.01.
The previous version failed to compile on my 10.5.8 PPC PowerBook PPC:


  /usr/bin/gcc-4.2 -c -I.  -Iimportinc -Iimportinc/netpbm -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_netpbm/netpbm/work/advanced/converter/pbm  -DNDEBUG -I/opt/local/include -Os -arch ppc    -o pbmtog3.o pbmtog3.c
  In file included from pbmtog3.c:25: importinc/netpbm/wordaccess.h:52:15: error: #include expects "FILENAME" or <FILENAME>
  In file included from pbmtog3.c:26: importinc/netpbm/wordintclz.h:21: error: expected ?)? before ?const?


This is fixed in 10.64.01 but the new version fails to compile with this error;


  /usr/bin/gcc-4.2 -c -I.  -Iimportinc -Iimportinc/netpbm -I/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_graphics_netpbm/netpbm/work/advanced/converter/other/jpeg2000  -I/opt/local/include -DNDEBUG  -I/opt/local/include -Os -arch ppc    -o pamtojpeg2k.o pamtojpeg2k.c
  pamtojpeg2k.c: In function ?parseCommandLine?:
  pamtojpeg2k.c:153: error: ?false? undeclared (first use in this function)
  pamtojpeg2k.c:153: error: (Each undeclared identifier is reported only once
  pamtojpeg2k.c:153: error: for each function it appears in.)


The new patch-lib-util-pm_c_util.h.diff patch addresses this by
replacing 'true' with '1' and 'false' with '0' which will work with
any C compiler, no matter how old.


git-svn-id: http://svn.macports.org/repository/macports/trunk@112198 d073be05-634f-4543-b044-5fe20cf6d1d6